### ISSUE TITLE
download M2I dataset

### ISSUE THREAD

**Issue by Levigty** [tmanh/srnn#2]
I could not download the M2I dataset at the moment. The author of the dataset has not replied to me. I happened to see your project on github. It's very kind of you if you can send me the original skeleton data of the M2I dataset.

**Comment by tmanh** [comment]
I am really sorry for the M2I dataset, but I don't have it with me. Now, I am working for another lab. I think the author left his university, and the university also removed everything of him. So, the dataset might be gone forever.

But, you can download this dataset instead https://github.com/shahroudy/NTURGB-D

This dataset is way bigger and harder than M2I. So, you can play with this dataset instead.

**Comment by Levigty** [comment]
Thank you for your reply and suggestion. The experiment of the NTU RGB+D dataset has already been done. I want to make the experiment more abundant, so I want to experiment on M2I dataset. I will think of other ways again. Thank you again.

**Comment by immkapoor** [comment]
@Levigty Hi i am also been looking for M2I dataset. Have you found it ?

**Comment by tmanh** [comment]
> @Levigty Hi i am also been looking for M2I dataset. Have you found it ?

Hi, the only way to access the dataset is via the author. You can send emails to them, but I do not know they are still active anymore.

**Comment by Levigty** [comment]
> @Levigty Hi i am also been looking for M2I dataset. Have you found it ?
I have previously sent emails to the corresponding author and other related authors, but I have not received a reply. Even if I asked my friend who studies at tju, it is currently difficult to obtain the dataset. For interactive action recognition, I use the SBU dataset and NTU RGB+D 60 dataset. Maybe you can try NTU RGB+D 120 dataset.

**Comment by immkapoor** [comment]
@Levigty I actually found the datwset to be interesting as it has synchronized views between two cameras (instead of a thermal sensor ). I ain't sure if there is similar dataset available
