### ISSUE TITLE
DataSet

### ISSUE THREAD

**Issue by Zhang-KL** [tmanh/srnn#3]
Hi, how was your CAD-120 dataset obtained and is it convenient to provide?

**Comment by tmanh** [comment]
Hi, I have left my institute 2 years ago and I don't have a copy of the CAD-120 dataset. The website of the dataset has been down for some reasons, so I think the best way is to contact the author of the dataset to check if they still keep the dataset. This is the linkedIn of the author https://www.linkedin.com/in/hemakoppula. Hope it works for you.
